### ISSUE TITLE
HOW to change NDArray to C#'s int[]

### ISSUE THREAD

**Issue by hawkcoder** [SciSharp/Numpy.NET#40]
`var data = np.array(new int[] {1, 2, 3, 4})`

how change `data` to `int[]` ?

**Comment by henon** [comment]
I extended the documentation with an example:

### Create a Numpy array from a C# array and vice versa

To work with data from C# in Numpy it has to be copied into the Python engine by using `np.array(...)`. You get an NDarray that you can use for further processing of the data. Here we calculate the square root:

```csharp
// create an NDarray from a C# array
var a = np.array(new[] { 2, 4, 9, 25 });
Console.WriteLine("a: "+ a.repr);
// a: array([ 2,  4,  9, 25])
// apply the square root to each element
var roots = np.sqrt(a);
Console.WriteLine(roots.repr);
// array([1.41421356, 2.        , 3.        , 5.        ])
```

After processing the data you can copy it back into a C# array use `a.GetData<int>()`, but be aware of the datatype of the NDarray in order to get correct values back:

```csharp
// Copy the NDarray roots into a C# array from NDarray (incorrect datatype)
Console.WriteLine(string.Join(", ", roots.GetData<int>()));
// 1719614413, 1073127582, 0, 1073741824 
Console.WriteLine("roots.dtype: " + roots.dtype);
// roots.dtype: float64
Console.WriteLine(string.Join(", ", roots.GetData<double>()));
// 1.4142135623731, 2, 3, 5
```

**Comment by rsinghbu-65** [comment]
How do we do this for` int[,] `? 
I get `Can not copy the data with data type due to limitations of Marshal.Copy: Int32[]`

**Comment by henon** [comment]
yeah, it doesn't work. you need to use `int[]` and calculate the index position yourself when accessing the data in c#. if you want help you can use my library SliceAndDice which allows you to reshape in c# and use like a numpy array.

**Comment by henon** [comment]
https://github.com/henon/SliceAndDice
