### ISSUE TITLE
Convert C# variables to np.NDarray and vice versa

### ISSUE THREAD

**Issue by natank1** [SciSharp/Numpy.NET#9]
Hi

I am new to keras.net. One question that is not clear for me. When I call such class I give it as inputa C# varaibles such as list <> or array.  I can convert these variables to numpy (array and ndarray) using loops but what are the generic function to convert
List <>  ->\np.array \np.NDarray
 \np.array \np.NDarray ->List<> \C# array

Thanks
Natan

**Comment by henon** [comment]
The most efficient way to pass large amounts of data into NDarray is by using np.array(T[], ... ). We implemented it so that the whole array will be copied into Numpy's storage with one single Marshal.Copy which is pretty fast. 

You can not do that with a List however. I suggest not to use List<> or .ToArray() the list. You best change your code to use arrays from the beginning i.e. by fixing the number of elements you want to process.

As for getting the data back out there is GetData<T>() which also copies the entire memory block in one go.

**Comment by natank1** [comment]
Thanks!!
